const exampleRecipes = [
    {
        "title": "Thai Sausage Salad",
        "image": "https://spoonacular.com/recipeImages/663149-312x231.jpg",
        "summary": "You can never have too many Asian recipes, so give Thai Sausage Salad a try. This recipe serves 2. One portion of this dish contains approximately <b>45g of protein</b>, <b>68g of fat</b>, and a total of <b>939 calories</b>. For <b>$4.25 per serving</b>, this recipe <b>covers 37%</b> of your daily requirements of vitamins and minerals. It is a good option if you're following a <b>gluten free and dairy free</b> diet. It is brought to you by Foodista. 1 person has made this recipe and would make it again. A mixture of green onions, thai fish sauce, lime juice, and a handful of other ingredients are all it takes to make this recipe so delicious. It works well as a rather pricey main course. From preparation to the plate, this recipe takes roughly <b>roughly 45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 65%</b>, which is solid. Users who liked this recipe also liked <a href=\"https://spoonacular.com/recipes/thai-sausage-rolls-119484\">Thai Sausage Rolls</a>, <a href=\"https://spoonacular.com/recipes/falconettis-chicken-thai-sausage-302425\">Falconetti's Chicken Thai Sausage</a>, and <a href=\"https://spoonacular.com/recipes/thai-style-sausage-and-rice-dressing-212353\">Thai-Style Sausage and Rice Dressing</a>.",
    },
    {

        "title": "Crock Pot Chili with Beans",
        "image": "https://spoonacular.com/recipeImages/640859-312x231.jpg",
        "summary": "Forget going out to eat or ordering takeout every time you crave American food. Try making Crock Pot Chili with Beans at home. This recipe serves 12. This main course has <b>200 calories</b>, <b>22g of protein</b>, and <b>5g of fat</b> per serving. For <b>97 cents per serving</b>, this recipe <b>covers 16%</b> of your daily requirements of vitamins and minerals. From preparation to the plate, this recipe takes approximately <b>approximately 45 minutes</b>. <b>The Super Bowl</b> will be even more special with this recipe. A mixture of pinto beans, to serve: cheese, additional salt and pepper, and a handful of other ingredients are all it takes to make this recipe so tasty. 1 person were glad they tried this recipe. It is a good option if you're following a <b>gluten free</b> diet. It is brought to you by Foodista. All things considered, we decided this recipe <b>deserves a spoonacular score of 74%</b>. This score is solid. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/crock-pot-chili-chili-and-beans-102738\">Crock Pot Chili Chili and Beans</a>, <a href=\"https://spoonacular.com/recipes/crock-pot-chili-con-carne-with-beans-145959\">Crock Pot Chili Con Carne With Beans</a>, and <a href=\"https://spoonacular.com/recipes/6th-annual-chili-contest-entry-6-crock-pot-jalapeno-popper-white-chicken-chili-689981\">6th Annual Chili Contest: Entry #6 – Crock Pot Jalapeno Popper White Chicken Chili</a>.",
    },
    {
        "title": "Simply Bean Soup",
        "image": "https://spoonacular.com/recipeImages/660161-312x231.jpg",
        "summary": "If you want to add more <b>gluten free and lacto ovo vegetarian</b> recipes to your recipe box, Simply Bean Soup might be a recipe you should try. One portion of this dish contains about <b>16g of protein</b>, <b>25g of fat</b>, and a total of <b>694 calories</b>. This recipe serves 1. For <b>$7.64 per serving</b>, this recipe <b>covers 23%</b> of your daily requirements of vitamins and minerals. It works well as a main course. 3 people were glad they tried this recipe. It is perfect for <b>Autumn</b>. This recipe from Foodista requires chicken broth, onion, sherry, and basil. From preparation to the plate, this recipe takes roughly <b>roughly 45 minutes</b>. With a spoonacular <b>score of 41%</b>, this dish is solid. <a href=\"https://spoonacular.com/recipes/simply-elegant-tomato-soup-425246\">Simply Elegant Tomato Soup</a>, <a href=\"https://spoonacular.com/recipes/simply-delicious-rice-soup-458209\">Simply Delicious Rice Soup</a>, and <a href=\"https://spoonacular.com/recipes/simply-perfect-cream-of-broccoli-soup-109952\">Simply Perfect Cream of Broccoli Soup</a> are very similar to this recipe.",
    },
    {
        "title": "Antipasto Squares",
        "image": "https://spoonacular.com/recipeImages/715511-312x231.jpg",
        "summary": "You can never have too many hor d'oeuvre recipes, so give Antipasto Squares a try. This recipe serves 6 and costs $3.22 per serving. One serving contains <b>737 calories</b>, <b>30g of protein</b>, and <b>51g of fat</b>. 831 person have made this recipe and would make it again. Head to the store and pick up pepperoni sausage, provolone cheese, roasted peppers, and a few other things to make it today. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 61%</b>. This score is good. Try <a href=\"https://spoonacular.com/recipes/italian-antipasto-squares-107702\">Italian Antipasto Squares</a>, <a href=\"https://spoonacular.com/recipes/couscous-antipasto-salad-with-tomato-vinaigrette-plus-antipasto-skewers-514571\">Couscous Antipasto Salad with Tomato Vinaigrette PLUS Antipasto Skewers</a>, and <a href=\"https://spoonacular.com/recipes/antipasto-86668\">Antipasto</a> for similar recipes.",
    },
    {

        "title": "Salsa Chicken & Black Beans",
        "image": "https://spoonacular.com/recipeImages/659158-312x231.jpg",
        "summary": "The recipe Salsa Chicken & Black Beans could satisfy your Mexican craving in around <b>45 minutes</b>. This recipe makes 2 servings with <b>399 calories</b>, <b>38g of protein</b>, and <b>8g of fat</b> each. For <b>$1.88 per serving</b>, this recipe <b>covers 29%</b> of your daily requirements of vitamins and minerals. Only a few people made this recipe, and 1 would say it hit the spot. It works well as a main course. A mixture of veggie broth, onion, salsa, and a handful of other ingredients are all it takes to make this recipe so scrumptious. To use up the juice of lime you could follow this main course with the <a href=\"https://spoonacular.com/recipes/cranberry-orange-juice-slushee-128682\">Cranberry-Orange Juice Slushee</a> as a dessert. It is a good option if you're following a <b>gluten free and dairy free</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 73%</b>. This score is good. Similar recipes include <a href=\"https://spoonacular.com/recipes/salsa-verde-chicken-with-black-beans-519056\">Salsa Verde Chicken with Black Beans</a>, <a href=\"https://spoonacular.com/recipes/black-beans-and-rice-with-chicken-and-apple-salsa-36098\">Black Beans And Rice With Chicken And Apple Salsa</a>, and <a href=\"https://spoonacular.com/recipes/vegetable-salsa-with-black-beans-avocado-664595\">Vegetable Salsa With Black Beans & Avocado</a>.",

    }
]

export default exampleRecipes